[Bugfix] about request.session
*AttributeError at /slo/post: 'LogoutProcessView' object has no attribute 'processor'*
- hasattr is important to avoid response that do not use any processors

*AttributeError at /slo/post: 'HttpResponseBadRequest' object has no attribute 'session'*
- store_params_in_session should not return a type, otherwise in an exception occourred it will return HttpResponseBadRequest
- store_params_in_session should not return a type, because request is written as a pointer and should not be overwritten by itself
If you don't like this programming code we could trnasfrom store_params_in_session in a decorator

Now SLO works again, please use for tests a SAML2 SP that implements SLO like sp configuration available in the example folder.