Pr 40 (#49)
* Made processor an instance variable

* Replaced outdated super()

* Brought out creation and rendering of response into methods in IdPHandlerViewMixin, made outgoing POST binding responses use the login.html template so that can be overriden

* Took out several major components (ie building authn response, sp information, getting authn), and put them into the mixin, so that less code is repeated between LoginProcess and SSOInit

* Removed unnecessary constant naming for AUTHN_BROKER

* Fixed bug that always sets processor to default

* Properly fixed it this time

* Added option to override sign response, sign assertion, and NameID field per each SP

* Minor stylistic abbreviation

* Modified documentation to explain new configurable changes for SP settings

* Added some more tests

* Ignored vscode config in gitignore

* Simplified create_identity a bit. This is a breakng change for custom processors

* Added support for methods to create_identity, + relevant unit test

Note: The dict comprehension was rewritten explicitly to prevent the code mess of trying to put conditional calling or not into a comprehension

* Fixed assert statement to test against actual thing in test for get_authn with no req_info

* Added documentation for using methods in attribute mapping

* Added pylama in requirements-dev.txt and fixed some pycodestyle

* Debug logging improved with pretty repr of SAML request/response in SSO

* Signature verification fixed TODO in LoginProcessView.get

* Style reverted from multiline to single line, TODO: write this in CONTRIBUTORS.md

* SSOInitView is not used...

* Additional style correction to single-line

May revert later after discussion of maintainer of main branch

* SLO support [HTTP-REDIRECT and HTTP-POST]

In addition:
- urls.py refactored, less code same features
- some code and function decopling in views.py (more would come in the future)
- idp example setup with SLO endpoint
- gettext lazy localizazion in view (internazionalization support)

* Additional style correction to single-line

May revert later after discussion of maintainer of main branch

* enabled signature_verification in SLO

* minor changes before merge

* Simplified overriding MultiFactor class

* Simplified getting custom multifator view with django import_string

* Removed unnecessary assignment of Signature and SigAlg from POST/GET params to session dict

This was removed for the following reasons:
1. A significant proportion of SPs do not send the signature or sigalg as a param with the request; it's enclosed in the actual SAMLRequest XML. As such, verification should extract it from there.
2. This is not used anywhere else in the code

* Simplified unnecesary intermediate variable

* Minor code style corrections in compliance with primary maintainer preferences

* Removed unnecessary processor check. Cant get to this stage without a processor

* Removed unnecessary template param

It will always use this template by default, so no need to have it as a parameter. It has been set as an intermediate variable for clarity's sake

* Simplified unnecessary method, clarified exception-handling, rearranged some methods to more logical order, renamed method to put query params into request session

* Reorganized a bit to remove excessive code

* [Bugfix] about request.session

*AttributeError at /slo/post: 'LogoutProcessView' object has no attribute 'processor'*
- hasattr is important to avoid response that do not use any processors

*AttributeError at /slo/post: 'HttpResponseBadRequest' object has no attribute 'session'*
- store_params_in_session should not return a type, otherwise in an exception occourred it will return HttpResponseBadRequest
- store_params_in_session should not return a type, because request is written as a pointer and should not be overwritten by itself
If you don't like this programming code we could trnasfrom store_params_in_session in a decorator

Now SLO works again, please use for tests a SAML2 SP that implements SLO like sp configuration available in the example folder.

* Added codecov

* Added support for methods to custom NameID field

* Removed unnecessary whitespace (code style)

* Removed unused import (code style)

* Fixed code style issues in example setup settings.py

* Added config to Travis to support testing with Python 3.7

* Removed test for Django 2.1 with python 3.4 b/c not supported

* Set zlib to automatically determine wbits size

* Added tests for utils, reworked encode_saml to be more functional

* Added namespace for reverse url call

* Resolved whitespace issues (code style)

* Added extensive tests

* Assorted bugfixes and minor improvements

* Signing and Digest algs configurable for every SP

* Added xmlsec1 install to travis, fixed various code style issues

* Added roadmap

* Removed codecov patch, as its been known to be bugged

* code style

* Signing and Digest algs configurable for every SP

* Encrypted assertion support

* IDP now answer only to SP that requests valid/available name_id formats

* NameID format builder

* encrypt_saml_responses per SP

* PersistentID now is salted with user.pk, in case of username reuse the PersistentID will not be the same

* sso_entry view now accepts keyword arguments, in case that's how they are provided

* updates

* cleanup

* updates on MR review

* remove sp & processor setting on self

* views cleanup

* cleanup

* changelog

* changelog updated

* update version number